"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import re
from setuptools import setup

def get_version():
    try:
        f = open("mist/_generated_version.py")
    except EnvironmentError:
        return None
    ver = None
    for line in f.readlines():
        mo = re.match("__version__ = '([^']+)'", line)
        if mo:
            ver = mo.group(1)
            break
    return ver



version = get_version()
print "version: ", version
APP = ['mist/mist.py']
APP_NAME = 'Mist'
DATA_FILES = ['mist/mist.py']
OPTIONS = {'argv_emulation': True,
# 'plist': 'Info_mist.plist',
 'plist': {
     'CFBundlePackageType': 'APPL',
     'CFBundleName': APP_NAME,
     'CFBundleDisplayName': APP_NAME,
     'CFBundleIdentifier': 'it.fub.mist',
     'CFBundleVersion': version,
     'CFBundleShortVersionString': version,
     'NSHumanReadableCopyright': 'Copyright 2012-2016 Fondazione Ugo Bordoni',
     'CFBundleIconFile': 'mist.icns'
     },
 'resources': 'icons',
 'iconfile': 'mist.icns',
 'semi_standalone': False, 
}

setup(
    app=APP,
    name='Mist',
    version='%s' % version,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
