"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['nemesys/nemesysspeedtest.py']
DATA_FILES = ['nemesys/nemesysspeedtest.py']
OPTIONS = {'argv_emulation': True,
 'plist': 'Info_nemesysspeedtest.plist',
 'resources': 'icons',
 'iconfile': 'nemesys.icns',
 'semi_standalone': False, 
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
